const SEASON_LIST = [
  //정규 이벤트
  "NEW_YEARS_EVE_AND_DAY",
  "LUNAR_NEW_YEAR",
  "SUPER_BOWL_SUNDAY",
  "VALENTINE_DAY",
  "ST_PATRICKS_DAY",
  "EASTER",
  "MOTHERS_DAY",
  "FATHERS_DAY",
  "INDEPENDENCE_DAY",
  "DDC_BIRTHDAY",
  "LABOR_DAY",
  "HALLOWEEN",
  "VETERANS_DAY",
  "THANKSGIVING_DAY",
  "BLACK_FRIDAY",
  "CYBER_MONDAY",
  "CHRISTMAS_DAY",

  // 슬롯 공용
  "WILD_HONEY_JACKPOT",
  "ROLLING_IN_MORE_GOLD",
  "HIPHOP_HOGS",

  // 슬롯
  "SUPER_HOT_CACTUS",
  "THE_GREAT_CATCH",
  "TRIPLE_RUSH_777",
  "WILD_SAVANNA",
  "HONEYCOMB_QUEST",
];
